# Functions statements

In [16]:
import numpy as np
import pandas as pd
import datetime as dt
pd.options.mode.chained_assignment = None

# Load and cleaning the dataset

In [17]:
raw_data = pd.read_csv("raw_data.csv")
raw_data.drop(['Unnamed: 0','total_shipments'],axis='columns',inplace=True)
raw_data['release'] = raw_data['release'].replace(r'N/A ',np.NaN,regex=True)
raw_data

,name,developer,platform,genre,total_sales,na_sales,pal_sales,japan_sales,other_sales,release
0,Just Dance,Ubisoft,Series,Music,NaN,NaN,NaN,NaN,NaN,17th Nov 09
1,Guitar Hero,Harmonix,Series,Music,NaN,NaN,NaN,NaN,NaN,08th Nov 05
2,SingStar,London Studios,Series,Music,NaN,NaN,NaN,NaN,NaN,NaN
3,Dance Dance Revolution,Konami,Series,Music,NaN,NaN,NaN,NaN,NaN,26th Sep 98
4,Taiko no Tatsujin,Bandai Namco Studios,Series,Music,NaN,NaN,NaN,NaN,NaN,26th Oct 04
...,...,...,...,...,...,...,...,...,...,...
62177,Zoids Wild: Blast Unleashed,Outright Games,NS,Action,NaN,NaN,NaN,NaN,NaN,16th Oct 20
62178,Zoids Wild: King of Blast,Takara Tomy,NS,Action,NaN,NaN,NaN,NaN,NaN,28th Feb 19
62179,Zombeer,Padaone Games,WiiU,Action,NaN,NaN,NaN,NaN,NaN,NaN
62180,Zombie Brigade: No Brain No Gain,Cypron Studios,WiiU,Action,NaN,NaN,NaN,NaN,NaN,NaN
62181,ZOMBIE GOLD RUSH,Amazing Inc.,NS,Action,NaN,NaN,NaN,NaN,NaN,26th Oct 17

In [16]:
clean_data = raw_data.dropna(subset=['total_sales'], inplace=False)
clean_data['release'] = pd.to_datetime(clean_data['release']).dt.date


clean_data = clean_data.fillna(0)


sales_dic=['total_sales','na_sales','pal_sales','japan_sales','other_sales']

for sale in sales_dic:
    clean_data[sale] = clean_data[sale].replace('m','',regex=True).replace(0.00,0.01)
    
clean_data.rename(columns = {'pal_sales' : 'eu_sales'}, inplace = True)


clean_data['release_year'] = clean_data['release'].astype(str).str[:4]
clean_data.drop(['release'],axis='columns',inplace=True)


clean_data = clean_data.drop_duplicates(subset=['name','platform'])
clean_data = clean_data.reset_index(drop=True)
clean_data.to_csv("games_df.csv")
clean_data

,name,developer,platform,genre,total_sales,na_sales,eu_sales,japan_sales,other_sales,release_year
0,Just Dance 4,Ubisoft,Wii,Music,6.89,4.05,2.21,0.01,0.62,2012
1,Just Dance 2014,Ubisoft Paris,Wii,Music,3.89,1.91,1.66,0.01,0.33,2013
2,Just Dance 2015,Ubisoft Paris,Wii,Music,2.09,1.00,0.91,0.01,0.18,2014
3,Dance Central 2,Harmonix Music Systems,X360,Music,2.04,1.45,0.41,0.01,0.16,2011
4,Guitar Hero Live,FreeStyleGames,PS4,Music,1.21,0.52,0.49,0.01,0.20,2015
...,...,...,...,...,...,...,...,...,...,...
18744,Daredevil,Griptonite Games,GBA,Action,0.00,0.00,0.00,0.01,0.01,2003
18745,Silent Hill: Homecoming,Double Helix Games,PC,Action,0.00,0.01,0.00,0.01,0.00,2008
18746,Hulk,Radical Entertainment,PC,Action,0.00,0.01,0.00,0.01,0.01,2003
18747,Of Orcs and Men,Cyanide Studio,X360,Action,0.00,0.01,0.00,0.01,0.01,2012
18748,Shinobido: Tales of the Ninja,Acquire,PSP,Action,0.00,0.01,0.00,0.01,0.01,2007